# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:db_a_root:qT7Wz4H7U3WJ9vFg@tcp(3.34.50.72:3306)/bivdex_a"

tron:
  count: 100                                     # 生成数据数量, gen_a 有效
  address: "TDqSquXBgUCLYvYC4XZgrprLK589dkhSCf"  # 初始地址
  maxConcurrency: 10                             # 最大并发数
  maxDepth: 100                                  # 最大递归深度
  maxAddressesPerLevel: 1000                      # 每层最多处理的地址数量
  maxPagesPerAddress: 10                         # 每个地址最多查询的页数
  prefix: 3                                      # 前3
  suffix: 4                                      # 后4
   # pipei 模式配置
  pipei:
    runMinutes: 10  # 程序运行10分钟后重启
    recordThreshold: 10  # 当新增记录超过10条时重启
    gpuCount: 1     # 要跑的卡数量
    limit: 30000 # 最多跑多少任务

  # lianghao 模式配置
  lianghao:
    runMinutes: 15  # 程序运行15分钟后重启
    recordThreshold: 10  # 当新增记录超过10条时重启
    gpuCount: 1     # 要跑的卡数量
    suffix: "5"  # 靓号尾数
    limit: 30000 # 最多跑多少任务
