server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "info"
  stdout: true

database:
  default:
    link: "mysql:root:1qaz@WSX3edc@tcp(124.221.133.54:3307)/tron?charset=utf8mb4&parseTime=True&loc=Local"
    maxIdle: 10
    maxOpen: 500
    maxLifetime: 30

tron:
  api:
    baseURL: "http://104.233.192.15:8090"
    key: ""
    timeout: 30
    rateLimit:
      requestsPerSecond: 200
      bucket: 200
    usdt:
      contract: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
  
  balance:
    table: "t_order_from_address"
    concurrency: 200
    batchSize: 200
    cron: "0 */30 * * * *"

  count: 100
  address: "TDqSquXBgUCLYvYC4XZgrprLK589dkhSCf"
  maxConcurrency: 10
  maxDepth: 100
  maxAddressesPerLevel: 1000
  maxPagesPerAddress: 10
  prefix: 3
  suffix: 4
  pipei:
    runMinutes: 10
    recordThreshold: 10
    gpuCount: 1
    limit: 30000

  lianghao:
    runMinutes: 15
    recordThreshold: 10
    gpuCount: 1
    suffix: "5"
    limit: 30000
