// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"sync"

	"tron-lion/internal/dao/internal"
	"tron-lion/internal/model/entity"
)

// tAddressOrderDao is the data access object for the table t_address_order.
// You can define custom methods on it to extend its functionality as needed.
type tAddressOrderDao struct {
	mu sync.Mutex
	*internal.TAddressOrderDao
}

var (
	// TAddressOrder is a globally accessible object for table t_address_order operations.
	TAddressOrder = tAddressOrderDao{
		TAddressOrderDao: internal.NewTAddressOrderDao()}
)

// Add your custom methods and functionality below.

func (t *tAddressOrderDao) Upsert(ctx context.Context, data []*entity.TAddressOrder) error {
	t.mu.Lock()
	defer t.mu.Unlock()
	_, err := t.Ctx(ctx).Data(data).
		OnDuplicate("address", "query_time", "balance").
		Save()

	return err
}

// FindOne 根据地址查询一条记录
func (t *tAddressOrderDao) FindOne(ctx context.Context, address string) (*entity.TAddressOrder, error) {
	var result *entity.TAddressOrder
	err := t.Ctx(ctx).Where("address", address).Scan(&result)
	if err != nil {
		return nil, err
	}
	return result, nil
}
