// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"tron-lion/internal/dao/internal"
)

// tOrderFromAddressDao is the data access object for the table t_order_from_address.
// You can define custom methods on it to extend its functionality as needed.
type tOrderFromAddressDao struct {
	*internal.TOrderFromAddressDao
}

var (
	// TOrderFromAddress is a globally accessible object for table t_order_from_address operations.
	TOrderFromAddress = tOrderFromAddressDao{internal.NewTOrderFromAddressDao()}
)

// Add your custom methods and functionality below.
