// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"tron-lion/internal/dao/internal"
)

// tOrderToAddressRecordDao is the data access object for the table t_order_to_address_record.
// You can define custom methods on it to extend its functionality as needed.
type tOrderToAddressRecordDao struct {
	*internal.TOrderToAddressRecordDao
}

var (
	// TOrderToAddressRecord is a globally accessible object for table t_order_to_address_record operations.
	TOrderToAddressRecord = tOrderToAddressRecordDao{internal.NewTOrderToAddressRecordDao()}
)

// Add your custom methods and functionality below.
