// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"tron-lion/internal/dao/internal"
)

// tReceiveOrderDao is the data access object for the table t_receive_order.
// You can define custom methods on it to extend its functionality as needed.
type tReceiveOrderDao struct {
	*internal.TReceiveOrderDao
}

var (
	// TReceiveOrder is a globally accessible object for table t_receive_order operations.
	TReceiveOrder = tReceiveOrderDao{internal.NewTReceiveOrderDao()}
)

// Add your custom methods and functionality below.
